[package]
name = "nostrss-cli"
version = "0.4.0-alpha"
edition = "2021"

[dependencies]
clap = { version = "4.1.3", features = ["derive"] }
serde = "1.0.152"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
log = "0.4.17"
tonic = "0.9.2"
tabled = "0.12.0"
url = "2.3.1"
cron = "0.12.0"

[dependencies.nostrss_grpc]
path = "../nostrss-grpc"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
panic = "abort"
