[package]
name = "nostrss"
version = "1.1.0"
edition = "2021"

[dependencies]
serde = "1.0.217"
serde_json = "1.0.135"
tokio = { version = "1.43.1", features = ["full"] }
nostr-sdk = "0.30.0"
tungstenite = { version = "0.26.1", features = ["rustls-tls-webpki-roots"]}
clap = { version = "4.5.24", features = ["derive"] }
tokio-cron-scheduler = "0.15.1"
reqwest = "0.13.2"
serde_yml = "0.0.12"
dotenv = "0.15.0"
quick-xml = "0.37.2"
log = "0.4.22"
atom_syndication = "0.12.6"
feed-rs = "2.3.1"
async-trait = "0.1.85"
env_logger = "0.11.6"
uuid = "1.11.0"
openssl = { version = "0.10.72", features = ["vendored"] }
new_string_template = "1.5.3"
regex = "1.11.1"
tonic = { version = "0.14.5", features = ["transport"] }
url = "2.5.4"

[dev-dependencies]
tempfile = "3.15.0"
mockall = "0.13.1"
mime = "0.3.17"
mediatype = "0.19.18"
[dependencies.nostrss_grpc]
path = "../nostrss-grpc"


