[package]
name = "nostrss"
version = "1.0.0-beta"
edition = "2021"

[dependencies]
serde = "1.0.183"
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["full"] }
nostr-sdk = "0.24.0"
tungstenite = { version = "0.20.0", features = ["rustls-tls-webpki-roots"]}
clap = { version = "4.3.5", features = ["derive"] }
tokio-cron-scheduler = "0.9.4"
reqwest = "0.11.18"
serde_yaml = "0.9.21"
dotenv = "0.15.0"
quick-xml = "0.30.0"
md5 = "0.7.0"
log = "0.4.19"
atom_syndication = "0.12.1"
feed-rs = "1.3.0"
bytes = "1.4.0"
async-trait = "0.1.68"
env_logger = "0.10.0"
uuid = "1.3.4"
openssl = { version = "0.10.56", features = ["vendored"] }
new_string_template = "1.4.0"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
regex = "1.9.3"
tonic = "0.10.0"
url = "2.4.1"

[dev-dependencies]
tempfile = "3.6.0"
mockall = "0.11.4"
mime = "0.3.17"

[dependencies.nostrss_grpc]
path = "../nostrss-grpc"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
panic = "abort"

[build-dependencies]
tonic-build = "0.9.2"
