[package]
name = "nostrss"
version = "1.0.1"
edition = "2021"

[dependencies]
serde = "1.0.199"
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
nostr-sdk = "0.30.0"
tungstenite = { version = "0.21.0", features = ["rustls-tls-webpki-roots"]}
clap = { version = "4.5.4", features = ["derive"] }
tokio-cron-scheduler = "0.10.2"
reqwest = "0.12.4"
serde_yaml = "0.9.34-deprecated"
dotenv = "0.15.0"
quick-xml = "0.31.0"
md5 = "0.7.0"
log = "0.4.21"
atom_syndication = "0.12.2"
feed-rs = "1.4.0"
bytes = "1.4.0"
async-trait = "0.1.80"
env_logger = "0.11.3"
uuid = "1.8.0"
openssl = { version = "0.10.64", features = ["vendored"] }
new_string_template = "1.5.1"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
regex = "1.10.4"
tonic = "0.11.0"
url = "2.5.0"

[dev-dependencies]
tempfile = "3.10.1"
mockall = "0.12.1"
mime = "0.3.17"

[dependencies.nostrss_grpc]
path = "../nostrss-grpc"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
panic = "abort"

[build-dependencies]
tonic-build = "0.11.0"
