[package]
name = "nostrss_grpc"
version = "1.0.0-beta"
edition = "2021"
build = "src/build.rs"

[dependencies]
prost = "0.11.9"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.9.2"
protoc = "2.28.0"
serde = "1.0.152"
[build-dependencies]
tonic-build = "0.9.2"