name: Build & Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: ⚒ Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: "1.85"
          components: rustc

    - name: Install protobuf dependency
      run: sudo apt-get -y install protobuf-compiler

    - name: ⚡ Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: 🏗 Build
      run: cargo build --verbose

    - name: 🎯 Run tests
      env:
        RUST_TEST_THREADS: 1
      run: cargo test --verbose

    - name: 🔒 Security audit
      run: |
        cargo install cargo-audit --quiet
        cargo audit
