name: Release
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


  test:
    name: Test
    needs: [style]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build: [stable, beta, nightly]
        include:
          - build: beta
            rust: beta
          - build: nightly
            rust: nightly
            benches: true

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          profile: minimal
          override: true

      - name: Build debug
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }}

      - name: Test all benches
        if: matrix.benches
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --benches ${{ matrix.features }}
  deploy:
    name: deploy
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target:  
          - aarch64-unknown-linux-gnu 
          - armv7-unknown-linux-gnueabihf 
          - i686-unknown-linux-gnu 
          - i686-unknown-linux-musl
          - arm-unknown-linux-gnueabi 
          - x86_64-unknown-linux-gnu 
          - x86_64-unknown-linux-musl
          - x86_64-unknown-netbsd
          # - aarch64-apple-darwin # CI fails as it appears that we have to use gcc provided by apple.
          # - x86_64-pc-windows-gnu # Currently release fails as compiled will have a .exe extension
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install ssl & musl
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev musl-tools
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/nostrss
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../nostrss-${{ matrix.target }}.tar.gz nostrss
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
            files: 'nostrss*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        